export const FETCH_BOOK_LIST_REQUEST = "FETCH_BOOK_LIST_REQUEST";
export const FETCH_BOOK_LIST_SUCCESS = "FETCH_BOOK_LIST_SUCCESS";
export const FETCH_BOOK_LIST_FAIL = "FETCH_BOOK_LIST_FAIL";

export const ADD_BOOK_REQUEST = "ADD_BOOK_REQUEST";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";
